### ISSUE TITLE
/home/container/modules/authentication.js:2 loginCommand = loginCommand.toString().replaceAll('passowrd', password)                                        ^ TypeError: loginCommand.toString(...).replaceAll is not a function     at Object.<anonymous> (/home/container/modules/authentication.js:2:40)

### ISSUE THREAD

**Issue by ME1SEGAWON** [dodoflix/minecraft-stress-tester#3]
/home/container/modules/authentication.js:2
loginCommand = loginCommand.toString().replaceAll('passowrd', password)
                                       ^
TypeError: loginCommand.toString(...).replaceAll is not a function
    at Object.<anonymous> (/home/container/modules/authentication.js:2:40)

**Comment by ME1SEGAWON** [comment]
how

**Comment by ME1SEGAWON** [comment]
loginCommand = loginCommand.toString().replaceAll('{password}', password)
                                       ^
TypeError: loginCommand.toString(...).replaceAll is not a function
    at Object.<anonymous> (/home/container/modules/authentication.js:2:40)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/home/container/index.js:19:29)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
